viewer/photos/urls.py
# viewer/photos/urls.py

from django.urls import path
from photos.views import dashboard, page, detail

app_name = "photos"

urlpatterns = [
    path("", dashboard, name="dashboard"), # <--- Dashboard View
    path("page/<int:page_num>", page, name="page"), # <--- Page View
    path("<int:pk>/", detail, name="detail"), # <--- Detail View
]

viewer/viewer/urls.py
# viewer/viewer/urls.py

"""viewer URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Viewer Site Administration"
admin.site.site_title = "Viewer Site Admin"

urlpatterns = [
    path('admin/', admin.site.urls), # ---> Admin Site
    path('', include('photos.urls')), # ---> Photos App
]

viewer/photos/models.py
# viewer/photos/models.py

import datetime
import logging

from django.db import models
from django.utils import timezone
from django.db.models import CharField, DateField, TextField

# Get instance of logger using namespace
logger = logging.getLogger(__name__)

class Photo(models.Model):
    name: CharField = models.CharField(
        max_length=25,
    )

    taken_date: DateField = models.DateField(
        blank=True,
    )

    pub_date: DateField = models.DateField(
        auto_now_add=True,
    )

    description: TextField = models.TextField(
        blank=True,
    )

    image = models.ImageField(
        blank=True,
        upload_to="static/images"
    )

    def __repr__(self) -> str:
        return f'{super().__class__()}: {self.name}'
    
    def __str__(self) -> str:
        return f'{self.name}'
    
    def was_published_recently(self) -> bool:
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

viewer/photos/views.py
# viewer/photos/views.py

import logging

from django.shortcuts import render
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.utils import timezone
from django.core.paginator import Paginator, Page
from django.views.decorators.http import require_POST

from photos.models import Photo

# Get instance of logger using namespace
logger = logging.getLogger(__name__)


def dashboard(request: HttpRequest) -> HttpResponse:
    photos = Photo.objects.all().filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')

    paginator = Paginator(photos, 12)
    page = paginator.page(1)

    return render(
        request,
        "photos/dashboard.html",
        {
            "page": page,
        }
    )


@require_POST
def page(request: HttpRequest, page_num: int) -> HttpResponse:
    photos = Photo.objects.all().filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')

    paginator = Paginator(photos, 12)
    current_page = paginator.page(page_num)

    hide_button = False

    if current_page.has_next():
        next_page = paginator.page(current_page.next_page_number())
        if not next_page.has_next():
            hide_button = True
        return render(
            request,
            "photos/photo_list.html",
            {
                "page": next_page,
                "hide_button": hide_button,
            }
        )
    else:
        hide_button = True
        return render(
            request,
            "photos/photo_list.html",
            {
                "hide_button": hide_button
            }
        )


def detail(request: HttpRequest, pk: int) -> HttpResponse:
    photo = Photo.objects.get(id=pk)
    return render(
        request,
        "photos/detail.html",
        {
            "photo": photo
        }
    )

viewer/photos/templates/base.html
<!-- viewer/photos/templates/base.html -->

{% load webpack_loader static %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% block page-title %}
        <title>PhotoView - Dashboard</title>
        {% endblock page-title %}
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        {% stylesheet_pack 'app' %}
        {% javascript_pack 'app' attrs='charset="UTF-8" defer'%}
        <style>
            .opacity {
                opacity: 1;
            }
            
            .opacity:hover {
                opacity: 0.7;
            }
            
            .zoom {
                transition: transform 0.2s !important; /* Animation */
            }
            
            .zoom:hover {
                transform: scale(1.05); /* (150% zoom - Note: if the zoom is too large,
                it will go outside of the viewport) */
            }
        </style>
    </head>
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <!-- Navbar Logo Image -->
                <a class="navbar-item" href="{% url 'photos:dashboard' %}">
                    <!-- TODO: Insert Logo Image -->
                    {% load static %}<img src="{% static 'images/' %}" alt="PhotoViewer Logo">
                </a>
                <!-- Navbar Burger and Menu Items -->
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <!-- Navbar Items -->
            <div id="Navbar" class="navbar-menu">
                <!-- Navbar Left-->
                <div class="navbar-start">
                    
                </div>
            </div>
        </nav>
        <div class="section">
            <div class="container">
                <!-- Main -->
                {% block main %}{% endblock main %}
                <!-- Modal -->
                {% block site-modal %}{% endblock site-modal %}
                <!-- JavaScript -->
                {% block site-script %}{% endblock site-script %}

                {% block page-script %}{% endblock page-script %}
            </div>
        </div>
    </body>
</html>

viewer/photos/templates/photos/dashboard.html
<!-- viewer/photos/templates/photos/dashboard.html -->

{% extends 'base.html' %}

{% block main %}
    <div class="section">
        <div class="container">
            <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
                <ul>
                    <li class="is-active"><a href="{% url 'photos:dashboard' %}" aria-current="page">Home</a></li>
                </ul>
            </nav>
            <!-- Header -->
            <header class="block">
                <h1 class="title is-1">PhotoViewer</h1>
                <p class="subtitle is-3">View photos here!</p>
            </header>

            <!-- Change Display -->
            <div x-data class="block">
                <div class="field has-addons">
                    <div class="control">
                        <button @click="$store.buttons.toggleListButton(), $store.buttons.toggleColumnButton()"
                            class="button is-medium"
                            :class="{ 'is-active is-success': $store.buttons.listButton, 'is-success is-light is-outlined': $store.buttons.columnButton }"
                        >
                            <span class="icon is-medium">
                                <i class="fa-solid fa-list fa-lg"></i>
                            </span>
                        </button>
                    </div>
                    <div class="control">
                        <button @click="$store.buttons.toggleColumnButton(), $store.buttons.toggleListButton()"
                            class="button is-medium"
                            :class="{ 'is-active is-success': $store.buttons.columnButton, 'is-success is-light is-outlined': $store.buttons.listButton }"
                        >
                            <span class="icon is-medium">
                                <i class="fa-solid fa-table-cells-large fa-lg"></i>
                            </span>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Photos -->
            <div class="block">
                <div x-data class="columns is-multiline" id="photos">
                    {% include 'photos/photo_list.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

viewer/photos/templates/photos/detail.html
<!-- viewer/photos/templates/photos/detail.html -->

{% extends 'base.html' %}

{% block page-title %}
    <title>PhotoViewer - {{ photo.name }}</title>
{% endblock page-title %}

{% block main %}
    <div class="section">
        <div class="container">
            <nav class="breadcrumb has-bullet-separator is-medium" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{% url 'photos:dashboard' %}">Home</a></li>
                    <li class="is-active"><a href="{% url 'photos:detail' photo.id %}" aria-current="page">{{ photo.name }}</a></li>
                </ul>
            </nav>
            <div class="box">
                <header class="block">
                    <h1 class="title is-1">{{ photo.name }}</h1>
                    <p class="subtitle is-3 has-text-grey-light">{{ photo.taken_date }}</p>
                </header>
                <figure class="block image is-5by4">
                    <img src="{{ photo.image.url }}">
                </figure>
                <div class="block content">
                    <span>{{ photo.description }}</span>
                    <span class="is-small has-text-grey-light">{{ photo.pub_date }}</span>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

viewer/photos/templates/photos/photo_list.html
<!-- viewer/photos/templates/photos/list.html -->


{% for photo in page %}    
    <div class="column is-full" :class="{ 'is-full': $store.buttons.listButton, 'is-one-third': $store.buttons.columnButton }">
        <div class="box flex-height">
            <figure class="block image is-5by4">
                <a href="{% url 'photos:detail' photo.id %}">
                    <img class="zoom" :class="{ 'zoom': $store.buttons.columnButton, 'opacity': $store.buttons.listButton }"
                        src="{{ photo.image.url }}"
                        alt="{{ photo.name }}"
                    >
                </a>
            </figure>
            <header class="block">
                <h2 class="title is-2"
                    :class="$store.buttons.listButton ? 'is-2' : 'is-3'"
                >
                    {{ photo.name }}
                </h2>
                <p class="subtitle is-4 has-text-grey-light"
                    :class="$store.buttons.listButton ? 'is-4' : 'is-5'"
                >
                    {{ photo.taken_date }}
                </p>
            </header>
            <p class="block">
                {{ photo.description }}
            </p>
        </div>
    </div>
{% endfor %}

{% if hide_button %}
    <div class="column is-full">
        <a href="#top" class="button is-large is-fullwidth is-primary is-light is-outlined">
            <span class="is-size-4 has-text-weight-semibold">Take me to the top!</span>
        </a>
    </div>
{% else %}
    <div id="replace-me" class="column is-full">
        <div class="field is-grouped">
            <div class="control is-expanded">
                <button class="button is-large is-fullwidth is-link is-light is-outlined"
                    hx-post="{% url 'photos:page' page.number %}"
                    hx-target="#replace-me"
                    hx-swap="outerHTML"
                >
                    <span class="is-size-4 has-text-weight-semibold">Load more pictures...</span>
                    {% load static %}<img class="htmx-indicator" src="{% static 'images/SVG-Loaders-master/svg-loaders/bars.svg' %}">
                </button>
            </div>
            <div class="control is-expanded">
                <a href="#top" class="button is-large is-fullwidth is-primary is-light is-outlined">
                    <span class="is-size-4 has-text-weight-semibold">Take me to the top!</span>
                </a>
            </div>
        </div>
    </div>
{% endif %}